### ISSUE TITLE
Add method that returns Page<T> to commons-data

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/backend-core#68]
I'm working in a project that uses the method with signature `Page<T> findAll(Pageable pageable)` from Spring Data `PagingAndSortingRepository` interface. As commons-data does not support it, I need to use a spring repository.
It would be useful to have an implementation this method in commons backend.

**Comment by mlopezFC** [comment]
The method `com.flowingcode.backendcore.service.QueryService.filter(QuerySpec)` supports paginated queries, and it is better because it only requires a QuerySpec that doesn't carry spring data dependencies to frontend layer.
