### ISSUE TITLE
Ease creation of QuerySpecs

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/backend-core#93]
If I want a QuerySpec that returns everything I need to:

```
    QuerySpec querySpec = new QuerySpec();
    querySpec.setFirstResult(0);
    querySpec.setMaxResult(Integer.MAX_VALUE);
```

Maybe it would be better to use something like QuerySpec.withNoRestrictions();

Also it would be great to have a builder pattern to make it easier to build a new instance.

**Comment by javier-godoy** [comment]
> If I want a QuerySpec that returns everything I need to:

If both `firstResult` and `maxResult` are `null`, it will be a non-paged query:
https://github.com/FlowingCode/backend-core/blob/6c23b719edaf5ecbbd3232a9a35d3a51aa5ff911/backend-core-business-spring-impl/src/main/java/com/flowingcode/backendcore/service/JpaCrudService.java#L102-L104

> Also it would be great to have a builder pattern to make it easier to build a new instance

+1
